### ISSUE TITLE
要如何分开使用呢？

### ISSUE THREAD

**Issue by RondaHo** [lovesunstar/STKit#1]
您好，技术哥！
我下载了您的这个库，看.h文件都是#import <STKit/xxxxx.h>这样的引用形式，你是把所有文件都打包了么。要怎么才能在项目中使用这些文件呢？我直接将STKit文件夹加入到工程，这样会报错找不到引用

**Comment by lovesunstar** [comment]
如果使用framework的方式，可以 #import <STKit/STKit.h>
但是STKit.h里面并未包含所有的文件，有单独使用的，可以 #import <STKit/STXXX.h>
如果你要使用代码的方式，可以直接拷贝文件以及依赖的文件。一般都依赖于 UIKit+STKit.h/Foundation+STKit.h

**Comment by RondaHe** [comment]
你#import的方式都是这样的
#improt < xxx/xxx.h>
我直接把代码放入项目中就会报错提示file not  find
改使用#impor "xxx.h" 这样的形式没问题，但是你的所有文件中都是#improt < xxx/xxx.h>这种形式，要改很多，我想是不是我哪里没设置对

**Comment by lovesunstar** [comment]
如果要使用全部文件的话，推荐使用workspace+STKit工程，这样也是可以直接Debug的。看你现在的情况，你需要修改为import "xx.h"

**Comment by RondaHe** [comment]
我将您的 stkit 工程加入到了我的 workspace。可以正常编译，但是不能#improt，还需要做什么设置呢？
![3a550bb1-aea8-4d19-8432-09a6b0a35d15](https://cloud.githubusercontent.com/assets/7590049/7999224/748272de-0b7a-11e5-81bf-9018210dced8.png)

**Comment by lovesunstar** [comment]
正常情况下，你需要设置searchPath 在 build-settings下直接搜索 search path 就可以看到，可以去查找相关的设置方法。

另外：xcode5 以后，你直接可以使用另一种方式，按下图所示，选择 autopackage， 然后Run。
![image](https://cloud.githubusercontent.com/assets/2378280/8000484/eadb1068-0b8d-11e5-97b6-b792faf9f863.png)
这个Target会跑一个自动打包脚本，等RunFinish以后，会自动打开一个文件夹，你把生成的Framework拖拽到你的工程中就可以了。

这种方式也是可以Debug STKit里面的内容的，并且你的工程每次都会去重新按需编译STKit。
使用的时候可以直接 import <STKit/STKit.h>
其他说明：STKit中由于网络方面使用到了gzip压缩，所以需要引入libz.dylib. 
或者在NSData+STGZip 将 #define STKit_STDefines_GZip 1 改为 0

**Comment by RondaHe** [comment]
技术哥，非常感谢您，通过编译产生Framework，然后加入工程后，在加入 libz.dylib系统库，完美运行。如果你更新了源码，或者我根据需求自行修改了源码只要再次打包成 framework，然后加入工程就好了吧？

**Comment by lovesunstar** [comment]
不需要重复操作。我更新了你只需要更新git就OK了，下次你运行你工程的时候会自动按需编译新的framework

**Comment by RondaHe** [comment]
哦哦，更新 git?  我项目中没有使用 git

**Comment by lovesunstar** [comment]
如果你修改了代码/下载到了新的代码，直接替换你workspace中的老代码，然后运行你的工程就可以了。不需要重新再此打包framework。

**Comment by RondaHe** [comment]
哦哦，原来是这样，非常感谢。低调的技术哥
